### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by mallorysmith64** [mallorysmith64/assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [x] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [x] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [x] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [x] Upload or submit a link to your resume for review.

**Comment by mallorysmith64** [comment]
[Mallory's Resume.pdf](https://github.com/mallorysmith64/assignments/files/3650428/Mallory.s.Resume.pdf)

**Comment by ktrammell95** [comment]
I think the overall look is beautiful and clean. I would think about moving the column width on the Education/ Experience side of it over so the Skills side is smaller and wraps the info more to take up more space.

To use up more space you could add lines for your GitHub link to each project and say a bit more about the project if you can think of anything else to add.
